<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_btn btn-default btn-xs removeMoney</name>
   <tag></tag>
   <elementGuidId>a7791f54-f3f1-4037-82fb-532a25ad28e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.btn-xs.removeMoney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='piggy-sortable']/tbody/tr[2]/td[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4827b766-f816-4bde-baa4-fd6538e72da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/remove/3</value>
      <webElementGuid>791b099d-f2d2-4e41-9be6-c38a7b8707ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-xs removeMoney</value>
      <webElementGuid>f4a585ea-9056-417f-9d23-0978d445c796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6b7a7ea1-6a71-467e-83ba-3e9e7fc3b238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piggy-sortable&quot;)/tbody[@class=&quot;piggy-connected-list ui-sortable&quot;]/tr[@class=&quot;piggy-sortable&quot;]/td[@class=&quot;hidden-sm hidden-xs&quot;]/a[@class=&quot;btn btn-default btn-xs removeMoney&quot;]</value>
      <webElementGuid>7b125e62-ace1-48c6-bade-3d85efe1b33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='piggy-sortable']/tbody/tr[2]/td[7]/a</value>
      <webElementGuid>0279a076-1d4d-447e-9192-da3eefea3b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/remove/3']</value>
      <webElementGuid>13888e89-335f-419b-be04-a0951234d4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>2977e4e3-1d39-43e7-b361-b3bee018b896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/remove/3']</value>
      <webElementGuid>ff757a8a-4fe0-41c3-bf29-b9eb0bc78729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
