<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_btn btn-default btn-xs addMoney</name>
   <tag></tag>
   <elementGuidId>736d2b20-5531-4c9b-a6ca-e3ca97fdd2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.btn-xs.addMoney</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='piggy-sortable']/tbody/tr[2]/td[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da53a3e6-cdc6-4323-a355-91ce05b9606d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/add/3</value>
      <webElementGuid>86311c15-2609-4ca0-a336-abe3a6a16bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-xs addMoney</value>
      <webElementGuid>dc7becd3-c009-4b9b-afa8-5c35c350e6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8650b628-3ae7-48dd-928e-6a33a169441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;piggy-sortable&quot;)/tbody[@class=&quot;piggy-connected-list ui-sortable&quot;]/tr[@class=&quot;piggy-sortable&quot;]/td[@class=&quot;hidden-sm hidden-xs&quot;]/a[@class=&quot;btn btn-default btn-xs addMoney&quot;]</value>
      <webElementGuid>415c821b-0342-446a-94ad-3b80330a07b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='piggy-sortable']/tbody/tr[2]/td[9]/a</value>
      <webElementGuid>061a30c9-9d82-454a-afaf-8b8a6ce45dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/add/3']</value>
      <webElementGuid>db1d4bac-aa10-4688-be68-58cb1b59c2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a</value>
      <webElementGuid>32d40612-8547-4fbe-b8dd-fac63bec4a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://ec2-3-26-8-206.ap-southeast-2.compute.amazonaws.com/piggy-banks/add/3']</value>
      <webElementGuid>5808640b-e9f0-407d-88f8-9b707933431c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
