<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit</name>
   <tag></tag>
   <elementGuidId>8157240b-c388-45e3-a65c-de050dc2eb47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9f8320a-37f8-4cb1-b0ef-5964a228ac44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5c0abb36-d63f-48fe-b621-994eccc245e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cad9f6ac-88f4-4bd6-8994-0c5c4320e9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete permanently</value>
      <webElementGuid>bce67323-961c-4f7a-b9d3-bdb41418c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger pull-right</value>
      <webElementGuid>1ff12d0d-9c7c-475c-a39e-149e1de90b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destroy&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-lg-offset-3 col-md-6 col-sm-12&quot;]/div[@class=&quot;box box-danger&quot;]/div[@class=&quot;box-footer&quot;]/input[@class=&quot;btn btn-danger pull-right&quot;]</value>
      <webElementGuid>1c4e4be8-7e43-4e41-8d77-ac068a215e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit']</value>
      <webElementGuid>e825191f-a280-46eb-aef3-d64c89dbac96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='destroy']/div/div/div/div[3]/input</value>
      <webElementGuid>b13dc9f3-b75b-45a4-92cd-eff27ad5e484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>38fb7b92-81ec-44b2-8c3c-6499471f9a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit']</value>
      <webElementGuid>2f9ddc3e-40b7-43c3-bc43-6ca6ce725cf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
