<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Savings Account (402.00)</name>
   <tag></tag>
   <elementGuidId>d1c12e03-482a-4910-a7a5-34774a6294e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.dropdown.open > ul.dropdown-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8ffe0ca-290c-4765-a17c-43006c37a7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1a8a529-76db-4e6a-a3db-f3c028b8d99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savings Account (€402.00)</value>
      <webElementGuid>0e61156c-a51b-4317-a137-fb2e0b94f4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/section[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>c41f9cfd-6982-419e-83d5-3da70d7917c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>4bc11cbe-0412-40d2-8d23-760a55f4d4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>908af828-9df1-479e-b95f-581492725ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Savings Account (€402.00)' or . = 'Savings Account (€402.00)')]</value>
      <webElementGuid>c5f7ea3d-a631-48ce-8436-2875a796a26e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
