<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Savings Account (702.00)</name>
   <tag></tag>
   <elementGuidId>9853d609-ca63-4564-b088-dc96c941d896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.dropdown.open > ul.dropdown-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7480c0a4-1ba5-4c6f-a67c-e3e7bfa5d6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efcbde14-65b6-4c82-b925-18193a59b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savings Account (€702.00)</value>
      <webElementGuid>80e8138b-91e8-4386-81dd-dc34a59b8ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/section[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>a55bb8e8-204f-43cf-9121-2cab775fc49a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>6954b6d1-a4b1-4807-b82a-84b7ee20899b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>da34a57e-27f9-4dd6-91f3-909956a705d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Savings Account (€702.00)' or . = 'Savings Account (€702.00)')]</value>
      <webElementGuid>2d91793d-48e1-41e7-be8b-ba68df49a951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
