<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error There was something wrong with yo_ffab21</name>
   <tag></tag>
   <elementGuidId>8ec65c5f-1fbc-4238-9682-60fd41fef88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/section[2]/form/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger.alert-dismissible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed73d501-c67f-4f2f-9c43-344d36841961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>a5fe8b29-99bb-40a9-b213-262901551308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger alert-dismissible</value>
      <webElementGuid>819845ac-915c-4dd7-a26e-47db04c177d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>× Error! There was something wrong with your submission. Please check out the errors.
            </value>
      <webElementGuid>7f7d1b71-3e7a-4858-a327-ff7b97656490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;alert alert-danger alert-dismissible&quot;]</value>
      <webElementGuid>04d14a6a-d50f-4c80-ac41-8cf5ee8c88ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/form/div/div/div</value>
      <webElementGuid>fb2e8ca3-005c-4640-89c6-b47f29f24454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>cb95cb40-cc5a-4d2b-b9c3-7f8d895fd054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '× Error! There was something wrong with your submission. Please check out the errors.
            ' or . = '× Error! There was something wrong with your submission. Please check out the errors.
            ')]</value>
      <webElementGuid>222ee233-9e95-46a4-8473-bc7f02a7a612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
