<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ti-new-tag-input ti-valid</name>
   <tag></tag>
   <elementGuidId>6148b8fb-cdc0-42e2-b73f-de02b46a34df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ti-new-tag-input.ti-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa889306-3bf8-4dc2-8952-b24dff164d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>e5ba6256-dcf8-4eed-8cee-a091f79502dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb6cbd8e-ee70-4de0-a591-025cd304207a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>533d6a6d-335d-4f8d-84d1-dcf1ae40a192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>31420ad0-80bb-49a7-9c09-55269a28599b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-new-tag-input ti-valid</value>
      <webElementGuid>3c96c9da-5366-47d3-ba89-4c0eadf5d6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;vue-tags-input force-background-tags-input&quot;]/div[@class=&quot;ti-input&quot;]/ul[@class=&quot;ti-tags&quot;]/li[@class=&quot;ti-new-tag-input-wrapper&quot;]/input[@class=&quot;ti-new-tag-input ti-valid&quot;]</value>
      <webElementGuid>dd62a497-d1f5-4d4c-8e68-30ea72ebfd0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>3f0eea58-4efe-49d0-bbe3-469afacc410d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[3]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>1611a24f-afa6-4d4d-8d0d-e19b8b9bca72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>43428301-036a-4b46-b49c-20cb8748de02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tags' and @type = 'text' and @title = 'Tags']</value>
      <webElementGuid>77e6d747-97f5-469d-a88c-61de1948f1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[4]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>1ba824bc-2891-4610-816c-8a0b5ee3cfab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
