<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checking Account (898.00)</name>
   <tag></tag>
   <elementGuidId>5d7a0a2f-81a6-43fd-9162-0a5d64437c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transaction-info']/div[2]/div[2]/section/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac02e549-4050-44e6-9edd-55d6900d555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27052359-0eb8-4be3-acdf-c64c7b61781a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checking Account (€898.00)</value>
      <webElementGuid>0d697a21-c787-4816-8d73-8022d5abd20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/section[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>9c6a0e14-866a-4e7c-9773-189ba5bc2b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transaction-info']/div[2]/div[2]/section/ul/li[4]/a</value>
      <webElementGuid>b38684b9-765f-4652-99a7-aa48751eadef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/ul/li[4]/a</value>
      <webElementGuid>5542b08e-687a-4daa-90cf-3c3c4b83d527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Checking Account (€898.00)' or . = 'Checking Account (€898.00)')]</value>
      <webElementGuid>b790faac-7927-4945-a0a0-83b6df19de54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
