<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Savings Account (102.00)</name>
   <tag></tag>
   <elementGuidId>9e46565c-e3c8-4aaf-a1f1-f3db9ba5895d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.dropdown.open > ul.dropdown-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e1ec05d-e7aa-4de1-85c2-11809c5029d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>026f7666-4214-4ce3-af8d-0cf14634dd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savings Account (€102.00)</value>
      <webElementGuid>06b57297-040c-4e67-a6f4-7cdcdbbb8bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/section[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>f1d407cb-c1fd-4ce5-bc92-3c53dfeafa27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transaction-info']/div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>dbd44d48-a524-4f46-a2e1-611b247c930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/section/ul/li[3]/a</value>
      <webElementGuid>72c85029-b9ef-44a4-bfb2-7f85c704cce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Savings Account (€102.00)' or . = 'Savings Account (€102.00)')]</value>
      <webElementGuid>49de2a0a-f61f-487d-bc0a-e2ef8a318ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
