<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>13748b97-795f-49ad-bf81-fd7cfb9db3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ffcf11b-1b98-4dfe-bdb2-750113105873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>e7b1e24a-a2cd-40f2-a377-efb4d98f44b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>70af5bb1-a799-461c-86d1-59224fc83270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit
                        </value>
      <webElementGuid>964d394c-a611-472b-bf8b-2968359ef283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitButton&quot;)</value>
      <webElementGuid>83eaf0f9-955a-4c3b-83a5-23fd3b017665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitButton']</value>
      <webElementGuid>c601c553-32e7-4004-b5f7-35972f8a78a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/form/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>9860ef43-2e04-4ffe-b1f9-f52967b689ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>4874b3fe-0e7a-4d1b-8d28-a15928009a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submitButton' and (text() = 'Submit
                        ' or . = 'Submit
                        ')]</value>
      <webElementGuid>d30a010a-0381-4950-b094-74e3807737ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
