<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ti-new-tag-input ti-valid</name>
   <tag></tag>
   <elementGuidId>8f0b9d82-6f7f-4535-abcc-d98142cf7452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ti-new-tag-input.ti-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c8c601-cac3-4cca-a36a-e43fea5d16c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>30f94047-61a0-4f8c-872b-e483b6d5daa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>630fe8ac-afa2-496f-b7bc-085642511d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27853d21-c67b-42d0-88ec-9ac277b35a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>300f9416-8293-4380-b7eb-5245213051c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-new-tag-input ti-valid</value>
      <webElementGuid>aae3b8fd-0b90-4292-967f-a9523bd97ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;vue-tags-input force-background-tags-input&quot;]/div[@class=&quot;ti-input&quot;]/ul[@class=&quot;ti-tags&quot;]/li[@class=&quot;ti-new-tag-input-wrapper&quot;]/input[@class=&quot;ti-new-tag-input ti-valid&quot;]</value>
      <webElementGuid>737c3f26-2367-45c6-a145-fbda1043fbd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>550110ff-01d9-4baa-ac13-c75c060d462a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[3]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>f0d481b2-b77c-48a2-ba4d-910fc9391957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>68809e12-954c-46b2-9989-455a508225c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tags' and @type = 'text' and @title = 'Tags']</value>
      <webElementGuid>e8d5865f-efb6-40f7-bd0f-c70ab5e49887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
