<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_The transaction amount must be less than_a8e23d</name>
   <tag></tag>
   <elementGuidId>4d6a50ad-40d2-49b0-8542-4219b5f81e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amount-info']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>98ad36f1-a5f2-4a8f-94a3-26a02041ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>857b1d0c-3fad-4015-81d2-4357fa8c2521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The transaction amount must be less than or equal 100001709.</value>
      <webElementGuid>aa05e95e-2bac-4af7-b80a-02dba8d3341d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount-info&quot;)/div[@class=&quot;form-group has-error&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>8bb03523-d41d-492e-ab4c-47b902f745ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount-info']/div/ul/li</value>
      <webElementGuid>2e2ecff0-0d56-4bf8-bf61-fb4affb57bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>4515345d-0fde-46c4-9055-d7dda15728a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'The transaction amount must be less than or equal 100001709.' or . = 'The transaction amount must be less than or equal 100001709.')]</value>
      <webElementGuid>9eb5291d-736c-4f6d-bd43-0d260f0f980b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
