<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ACB BankACB Bank savings accountCash wallet</name>
   <tag></tag>
   <elementGuidId>fc8a0354-d8f2-4c5b-ac65-9a5fd6de3692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_account_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_account_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f9f7023-6826-46fa-b0f5-dcb3c28a6673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2093fa1-ddf4-4034-82c6-394bea0dc164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_id</value>
      <webElementGuid>933af233-39e5-4bea-b0ce-54d0dc8658b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_account_id</value>
      <webElementGuid>d0243802-fdcd-4e97-b5b2-10d8ee9e9580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b1a2156-4162-480b-bfa8-068ca2c08e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4691e39e-17d1-47da-8a59-9640b9599230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACB BankACB Bank savings accountCash wallet</value>
      <webElementGuid>debaa8f9-3818-45d5-aa2b-12eaf6485fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_account_id&quot;)</value>
      <webElementGuid>b0b5c4f0-11aa-465a-ae30-7427f01c736d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_account_id']</value>
      <webElementGuid>ba668a8a-6065-48e8-80a4-c674a3cb841f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_id_holder']/div/select</value>
      <webElementGuid>b97169ff-d52e-415d-80c3-4e83d1e1a693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8127981d-a273-405c-96e5-e9388b859f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_id' and @id = 'ffInput_account_id' and (text() = 'ACB BankACB Bank savings accountCash wallet' or . = 'ACB BankACB Bank savings accountCash wallet')]</value>
      <webElementGuid>903c7d8b-42cf-4b8f-97ab-300da2cf768b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
