<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng nhp</name>
   <tag></tag>
   <elementGuidId>a5d31656-1a30-44fc-b45d-e372046f2534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/ul[2]/li/span/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-1g853jt.ant-btn-default > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b967a478-8dee-4703-9f8c-346f29bec3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/sign-in</value>
      <webElementGuid>d69248eb-9157-49c1-b199-4a720e5cecad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>6f4bb3f1-de71-4f9b-a284-7bc5acee275e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-layout layout css-1g853jt&quot;]/header[@class=&quot;ant-layout-header css-1g853jt&quot;]/ul[@class=&quot;ant-menu-overflow ant-menu ant-menu-root ant-menu-horizontal ant-menu-light css-1g853jt&quot;]/li[@class=&quot;ant-menu-overflow-item ant-menu-item ant-menu-item-active ant-menu-item-only-child&quot;]/span[@class=&quot;ant-menu-title-content&quot;]/button[@class=&quot;ant-btn css-1g853jt ant-btn-default&quot;]/a[1]</value>
      <webElementGuid>46c9288c-3d30-4d16-a908-fe44857fc3ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/ul[2]/li/span/button/a</value>
      <webElementGuid>60c1fbb3-fc76-481b-95f7-d477c443e814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng nhập')]</value>
      <webElementGuid>23407b83-3dd7-4309-a0db-4587afe67b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/sign-in')]</value>
      <webElementGuid>320802e5-07ee-4857-9698-627f63b12e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>8cb7a727-d421-4966-84bd-9c00b49222e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/sign-in' and (text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>d492e8f7-71c5-4c59-be37-e282dc15ff79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
