<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_To lp hc</name>
   <tag></tag>
   <elementGuidId>de5d4df9-eb84-410e-8b09-b69b333e15d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/aside/div/ul/li[3]/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-item.ant-menu-item-active > span.ant-menu-title-content > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48f9aa75-c799-4fc9-b03f-566b373e28e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/create-classroom</value>
      <webElementGuid>13deb0a5-3e6d-4ab1-aa7b-e44336fce2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tạo lớp học</value>
      <webElementGuid>ba297b1e-e3fe-4388-ace0-0c2fe7adb665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;ant-layout layout css-1g853jt&quot;]/main[@class=&quot;ant-layout-content css-1g853jt&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-1g853jt&quot;]/aside[@class=&quot;ant-layout-sider ant-layout-sider-dark&quot;]/div[@class=&quot;ant-layout-sider-children&quot;]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-inline ant-menu-light css-1g853jt&quot;]/li[@class=&quot;ant-menu-item ant-menu-item-active&quot;]/span[@class=&quot;ant-menu-title-content&quot;]/a[1]</value>
      <webElementGuid>a744602b-f6dc-41ab-b5c5-39263343323e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/aside/div/ul/li[3]/span[2]/a</value>
      <webElementGuid>9f9d4dcf-0fca-4a85-84cf-ec135a50bebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tạo lớp học')]</value>
      <webElementGuid>17111ba2-a48f-49eb-8bfd-5e97a5b5d8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/create-classroom')]</value>
      <webElementGuid>071e9c7d-5262-478f-8e78-ebc0edf3fd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span[2]/a</value>
      <webElementGuid>fa0513ad-1283-4b79-8fdd-1488c6687908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/create-classroom' and (text() = 'Tạo lớp học' or . = 'Tạo lớp học')]</value>
      <webElementGuid>ed89bfdd-ec9b-4376-9d29-17cf59c0ee1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
