<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng k</name>
   <tag></tag>
   <elementGuidId>96642dd5-0b0a-4e77-b614-76dd07809517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-1g853jt.ant-btn-primary.signup-form-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6981d92f-6980-405f-b5f2-5c389a3f8dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7082dc6-af77-436c-9a77-6da0657831d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1g853jt ant-btn-primary signup-form-button</value>
      <webElementGuid>d37fc45c-f80a-4a4f-ba98-8370eb4e42ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng kí</value>
      <webElementGuid>066bb852-a020-4477-847c-7741fca55048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup&quot;)/div[@class=&quot;ant-form-item css-1g853jt&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1g853jt&quot;]/div[@class=&quot;ant-col ant-col-16 ant-col-offset-8 ant-form-item-control css-1g853jt&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/button[@class=&quot;ant-btn css-1g853jt ant-btn-primary signup-form-button&quot;]</value>
      <webElementGuid>97c0519d-cffa-4b4e-813a-63fec11d2ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>321da51a-81c3-4e56-91f8-7989bad73002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div[9]/div/div/div/div/button</value>
      <webElementGuid>6aa3404f-522a-4af8-a0fb-ac86abf877af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>d61b595b-2976-4f86-9885-a01ee8ee41a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Đăng kí' or . = 'Đăng kí')]</value>
      <webElementGuid>c2fd7918-b206-4c34-b2ff-bd705fe0e99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
