<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnormal_signup_telephone</name>
   <tag></tag>
   <elementGuidId>205497f8-9988-4b6b-8433-48ec4b8a515e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_signup_telephone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normal_signup_telephone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ae5b0de-2f22-4994-a948-c3006de6641a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Telephone</value>
      <webElementGuid>d642a2a0-b5c0-43f9-abf9-029b8674554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>035fee3a-0539-4aea-9b39-52ad543b35a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_signup_telephone</value>
      <webElementGuid>fb70b2c0-ee27-432b-99b1-cf59a2299761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>312a0a7f-8a8d-4965-9384-845a85e37c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg ant-input-status-success css-1g853jt</value>
      <webElementGuid>f7408260-28f1-4460-b98c-adda104da4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25f17218-2f11-4711-91bb-c9b1888e2d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup_telephone&quot;)</value>
      <webElementGuid>121f8def-081e-420a-8ddb-8abc7e64a944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_signup_telephone']</value>
      <webElementGuid>cdc1f91f-afc4-4d4a-ad59-a47406c22069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>ba355214-9de4-49a8-ad73-d5ec3fd5b176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>3ed5c017-626f-481c-ac93-0a0fdb726f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Telephone' and @type = 'tel' and @id = 'normal_signup_telephone']</value>
      <webElementGuid>74fd3695-7cc7-47c8-aec9-f6315a93c6ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
