<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnormal_signup_fullname</name>
   <tag></tag>
   <elementGuidId>844cd0c6-e390-40c0-af30-71349cb042bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_signup_fullname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normal_signup_fullname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65f828ae-59c6-42a3-bc69-cc2adbccc4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fullname</value>
      <webElementGuid>18de01c6-5743-49a6-ac0b-e4af1b875b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_signup_fullname</value>
      <webElementGuid>71786aa0-5dd2-43c4-929a-d9a6a7ba54e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1baabf3a-fea2-413f-a3df-963b1f39f99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-1g853jt</value>
      <webElementGuid>f3e75835-254d-4c81-a724-71fe74e13340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>775a95f1-1018-45d5-baee-fae644ee44f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup_fullname&quot;)</value>
      <webElementGuid>bf047dca-c842-40f2-bccd-3ea80b42a66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_signup_fullname']</value>
      <webElementGuid>86acf265-2935-4523-9657-bd3563391675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div/div/div[2]/div/div/input</value>
      <webElementGuid>22900f5d-3976-49b1-9ce0-bc3fdbfa1602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1b6134bf-0c03-4ce8-a11a-26ca7f8a8e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Fullname' and @id = 'normal_signup_fullname' and @type = 'text']</value>
      <webElementGuid>7b87cf5d-cc71-4a1b-ad2c-7f13c1980216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
