<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputnormal_signup_classroomName</name>
   <tag></tag>
   <elementGuidId>e9253940-17b3-4bf8-899e-7816ff6003b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_signup_classroomName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normal_signup_classroomName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03a7de64-022a-4022-9032-0e566e8bc21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Classroom Name</value>
      <webElementGuid>ad556bbb-3e20-400d-a82d-b89324e9ca4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_signup_classroomName</value>
      <webElementGuid>5f28091e-135a-4f22-8273-4a5441f12918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aed23a9e-691c-4fac-bdd6-ae6a09fbfa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-1g853jt</value>
      <webElementGuid>e113c293-0b28-4fe6-8ec7-ae058221b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>deb02cf4-40e6-4f5e-8149-1bcf2d773eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup_classroomName&quot;)</value>
      <webElementGuid>1f9830e9-6d24-454d-ab61-d934ac382623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_signup_classroomName']</value>
      <webElementGuid>e479870b-abaa-4051-b294-110da014aa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div/div/div[2]/div/div/input</value>
      <webElementGuid>caf4fd28-3ec4-4acc-b15d-b7cc7aa43992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b444aab6-0502-4c63-a04b-1951a208d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Classroom Name' and @id = 'normal_signup_classroomName' and @type = 'text']</value>
      <webElementGuid>bd769680-9aad-423c-a31d-919daa9eecc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
