<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Classroom Name</name>
   <tag></tag>
   <elementGuidId>54c0400d-a88b-40e0-8674-ae3330d163aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='normal_signup']/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ant-form-item-required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fc9247cb-f81a-4fa9-828f-a0f887e8e6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>normal_signup_classroomName</value>
      <webElementGuid>eccb2f16-2f02-48dc-bd15-45e61d1c6b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-form-item-required</value>
      <webElementGuid>3c9a12a9-b634-41bc-bf81-f53138f7f1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Classroom Name</value>
      <webElementGuid>679cf4cf-8fd3-4b74-86f4-07e6568ba7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classroom Name</value>
      <webElementGuid>8418ddba-64f5-4233-93cc-c216d46f972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup&quot;)/div[@class=&quot;ant-form-item css-1g853jt ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1g853jt&quot;]/div[@class=&quot;ant-col ant-col-8 ant-form-item-label css-1g853jt&quot;]/label[@class=&quot;ant-form-item-required&quot;]</value>
      <webElementGuid>0de73bc1-963c-45b2-a2d4-f8d0047685f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div/div/div/label</value>
      <webElementGuid>17f6f072-6b44-4754-9380-537ab1b2744c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>55aa33f7-defb-4761-ad6d-a56afbb21090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Classroom Name' and (text() = 'Classroom Name' or . = 'Classroom Name')]</value>
      <webElementGuid>0ebba8d8-5a24-44f4-937f-6f868f02f8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
