<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sinh hc phn t</name>
   <tag></tag>
   <elementGuidId>f3ce500d-e218-4ec3-bd95-26178b2dafbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='normal_signup_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#normal_signup_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>86cbebb1-9ce5-49de-bdaa-7f788d4c26ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Classroom description</value>
      <webElementGuid>90fdbf6d-e85a-4d43-a6f2-01d5699af394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_signup_description</value>
      <webElementGuid>33151c4e-f5bb-402b-887a-16b900d54cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cbf302f-b87e-47af-9256-33577e05756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg ant-input-status-success css-1g853jt</value>
      <webElementGuid>9923009e-9089-4c78-bee6-b39ff047193b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sinh học phân tử</value>
      <webElementGuid>ca897845-33b8-4778-b7dd-11b9a432dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_signup_description&quot;)</value>
      <webElementGuid>afbaead5-630f-42f9-b8ab-2ea7be6b3367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='normal_signup_description']</value>
      <webElementGuid>f2fd6cad-cf98-43aa-b12d-84a9e3ca72e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_signup']/div[4]/div/div[2]/div/div/textarea</value>
      <webElementGuid>7900a614-3fb3-4187-9187-5df9fcd84573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1489aa6d-fec2-4fea-be68-f7006f150508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Classroom description' and @id = 'normal_signup_description' and (text() = 'Sinh học phân tử' or . = 'Sinh học phân tử')]</value>
      <webElementGuid>2f4ed7de-7a89-4a8f-9546-87b040c2a91f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
