<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clone</name>
   <tag></tag>
   <elementGuidId>412563eb-12f2-4c55-bcf5-5f2a40101efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.clone-transaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/section[2]/div[3]/div/div/div[2]/table/tbody/tr/td[8]/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>268735f7-3e82-4f92-adb8-8591105f9094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1b32665b-ab7c-4740-9f2f-fe3f45496400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>182</value>
      <webElementGuid>c8ed64f7-e177-465a-8aa7-3a5f5289ff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clone-transaction</value>
      <webElementGuid>15aab482-fec5-4962-9910-21dc81a1a4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clone</value>
      <webElementGuid>9d2c0d76-d3d2-4c53-9e7f-d2e232b71fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-md-10 col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body no-padding&quot;]/table[@class=&quot;table table-condensed table-hover table-responsive table-sortable&quot;]/tbody[1]/tr[1]/td[@class=&quot;hidden-xs&quot;]/div[@class=&quot;btn-group btn-group-xs pull-right open&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-right&quot;]/li[3]/a[@class=&quot;clone-transaction&quot;]</value>
      <webElementGuid>22bf4d46-f4a5-49ae-add1-ab4846ba75d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div[3]/div/div/div[2]/table/tbody/tr/td[8]/div/ul/li[3]/a</value>
      <webElementGuid>18189a74-f4e6-4497-8a60-7b6f4ad04874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clone')]</value>
      <webElementGuid>b0fed973-d86a-4d35-a122-a1b719a91150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>7ff1fdf6-6a80-49f9-95bf-fc4bd418040c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/ul/li[3]/a</value>
      <webElementGuid>8f7a06db-7905-4df0-a3db-2f8a4f81ba61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Clone' or . = ' Clone')]</value>
      <webElementGuid>3b3eaed7-4506-4ab0-b944-48272d9199b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
