<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Skip</name>
   <tag></tag>
   <elementGuidId>68184a81-253e-4e9c-8c0f-c5522ab688e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.introjs-button.introjs-skipbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Skip')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95d08878-684f-42fa-87f5-57ae94ea0a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-button introjs-skipbutton</value>
      <webElementGuid>d579e76c-a0ee-48b2-87c5-f6e921e6c308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc29e8a5-a44d-4c25-98da-62cb418872bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d8d0c6b-4c63-4df0-bbd9-012c0558e787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>6d46807d-84dd-48c3-a180-c5f102b73623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;skin-firefly-iii sidebar-mini&quot;]/div[@class=&quot;introjs-tooltipReferenceLayer&quot;]/div[@class=&quot;introjs-tooltip&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-button introjs-skipbutton&quot;]</value>
      <webElementGuid>c5d815a6-aed9-4212-8af6-751aebe63803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Skip')]</value>
      <webElementGuid>34bf0cb4-4bf1-4a96-96a6-50d8f16fe574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>fdefb5bc-7175-4ff9-abc7-42f4fbe1ef18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>f1a8ef76-ff30-450e-b3c6-e1aca1a3c953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
