<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Budgets</name>
   <tag></tag>
   <elementGuidId>49459704-d6a6-4dd5-9d76-d0c3bf7ef101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='budget-menu']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#budget-menu > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b430bf00-1c6b-4f53-bf1f-978e68e863d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8080/budgets</value>
      <webElementGuid>809f9f8a-c4f6-4fad-a5ae-8c26232ba8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Budgets
        </value>
      <webElementGuid>c416685e-36ef-4e79-96c3-9997bb04dde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budget-menu&quot;)/a[1]</value>
      <webElementGuid>f035415c-9133-4cf4-ad61-4b0f7876de93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='budget-menu']/a</value>
      <webElementGuid>ab2ffa34-b522-4a7f-9492-58c5b167d9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8080/budgets']</value>
      <webElementGuid>27de361a-66bd-4839-be34-55b6875d649c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>8e7fa981-7edb-4016-8cf9-10f1a3752426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8080/budgets' and (text() = '
            
            Budgets
        ' or . = '
            
            Budgets
        ')]</value>
      <webElementGuid>9e273b8f-faac-437d-ab4c-15027065a8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
