<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ti-new-tag-input ti-valid</name>
   <tag></tag>
   <elementGuidId>29036d83-907c-4a3c-bef4-8caee37af6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ti-new-tag-input.ti-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83c1a134-e804-4218-9805-09b88dc13320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>53af0379-2200-4fc0-bf32-6f626d744792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dffa7cc9-db3c-422a-8e06-2d81b26cbb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f77375ff-0068-498a-a275-2b119f0fbba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>808b511a-01eb-45d9-9a8a-3f8932842231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-new-tag-input ti-valid</value>
      <webElementGuid>698a4190-4916-49c9-ba37-9a4886df82bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;vue-tags-input force-background-tags-input&quot;]/div[@class=&quot;ti-input&quot;]/ul[@class=&quot;ti-tags&quot;]/li[@class=&quot;ti-new-tag-input-wrapper&quot;]/input[@class=&quot;ti-new-tag-input ti-valid&quot;]</value>
      <webElementGuid>2eed083e-e8dd-4134-8d6f-82d836503123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>2c717679-33d3-4ba6-a57f-00f182bcf0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[4]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>99026252-fe0a-4d6d-91c6-5293ffaff1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>6bfacfc4-87cb-42bf-a4af-63d3d0480fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tags' and @type = 'text' and @title = 'Tags']</value>
      <webElementGuid>a2835542-c14c-4aad-94c8-4b7546b932cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
